# base image
FROM ubuntu:22.04

#input GitHub runner version argument
ENV DEBIAN_FRONTEND=noninteractive
ARG PAT=""

LABEL Author="Bogdan Grozoiu"
LABEL BaseImage="ubuntu:22.04"

# update the base packages + add a non-sudo user
RUN apt-get update -y && apt-get upgrade -y && useradd -m docker -g root

# install the packages and dependencies along with jq so we can parse JSON (add additional packages as necessary)
RUN apt-get install -y --no-install-recommends \
    curl nodejs wget unzip vim git jq build-essential libssl-dev libffi-dev python3 python3-venv python3-dev python3-pip dpkg apt-transport-https software-properties-common

#install azure-cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# install powershell
RUN wget -q 'https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb' \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell \
    && rm -f packages-microsoft-prod.deb

#install AzModule
RUN pwsh -Command "Install-Module -Name Az -AllowClobber -Scope AllUsers -Force"

# cd into the user directory, download and unzip the github actions runner
RUN RUNNER_VERSION=$(curl -H "Authorization: token $PAT" 'https://api.github.com/repos/actions/runner/releases/latest' | jq -r '.tag_name[1:]') \
    && cd /home/docker && mkdir actions-runner && cd actions-runner \
    && curl -H "Authorization: token $PAT" -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

# install some additional dependencies
RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh

# add over the start.sh script
ADD bootstrap/start.sh start.sh

# make the script executable
RUN chmod +x start.sh

# set the user to "docker" so all subsequent commands are run as the docker user
USER docker

# set the entrypoint to the start.sh script
ENTRYPOINT ["./start.sh"]
