ARG BASEIMAGE=""

# base image
FROM $BASEIMAGE

#input GitHub runner version argument
ENV DEBIAN_FRONTEND=noninteractive
ENV TARGETARCH=linux-x64

ARG PAT=""

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y --no-install-recommends \
    curl \
    nodejs \
    wget \
    unzip \
    vim \
    git \
    jq \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3 \
    python3-venv \
    python3-dev \
    python3-pip \
    dpkg \
    apt-transport-https \
    software-properties-common

#install azure-cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# cd into the user directory, download and unzip the github actions runner
RUN RUNNER_VERSION=$(curl -H "Authorization: token $PAT" 'https://api.github.com/repos/actions/runner/releases/latest' | jq -r '.tag_name[1:]') \
    && mkdir ghrunner && cd ghrunner \
    && curl -H "Authorization: token $PAT" -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && rm -f ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && ./bin/installdependencies.sh

# install powershell
RUN wget -q 'https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb' \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell \
    && rm -f packages-microsoft-prod.deb

#install AzModule
RUN pwsh -Command "Install-Module -Name Az -AllowClobber -Scope AllUsers -Verbose -Force"

WORKDIR /ghrunner

ADD ./start.sh start.sh
RUN chmod +x start.sh

ENTRYPOINT ["./start.sh"]
